system:
  host: 0.0.0.0
  port: 24916
  username: admin
  password: admin

db:
  engine: postgres
  ssl_mode: disable
  host: 127.0.0.1
  port: 5432
  username: evobot
  password: Evobot!
  database: evobot

redis:
  host: 127.0.0.1
  port: 6379
  password: Evobot!
  database: 5
  pool_size: 100
  min_idle_conns: 0
  idleTimeout: 0

support:
  baseurl: 127.0.0.1
  username: admin
  password: Evobot!

auth:
  secret: "Evobot!"
  jwt_expired: 7200s

log:
  lang: "zh" # zh/en
  model: "dev"
  level: "debug"
  filename: "EvoBot.log"
  max_size: 200
  max_age: 30
  max_backups: 7
