system:
  host: 0.0.0.0
  port: 24916
  username: admin
  password: admin

db:
  engine: postgres
  ssl_mode: disable
  host: 127.0.0.1
  port: 5432
  username: mkics
  password: mkics
  database: mkics

redis:
  host: 127.0.0.1
  port: 6379
  password: mkics
  database: 5
  pool_size: 100
  min_idle_conns: 0
  idleTimeout: 0

auth:
  secret: "mkics"
  jwt_expired: 7200s

log:
  model: "dev"
  level: "debug"
  max_size: 200
  max_age: 30
  max_backups: 7

support:
  baseurl: 127.0.0.1
  username: mkics
  password: mkics