system:
  host: 127.0.0.1
  port: 24916
  username: admin
  password: admin

db:
  host: 127.0.0.1
  port: 3306
  username: evobot
  password: Evobot!
  database: evobot

redis:
  host: 127.0.0.1
  port: 6379
  password: Evobot!
  database: 5
  pool_size: 100
  min_idle_conns: 0
  idleTimeout: 0

auth:
  secret: "Evobot!"
  jwt_expired: 7200s

log:
  model: "dev"
  level: "debug"
  filename: "EvoBot.log"
  max_size: 200
  max_age: 30
  max_backups: 7
