on: [push, pull_request, release]

name: MKICS generic action handler

jobs:
  generic_handler:
    name: Generic handler for MKICS Repos
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: jumpserver/action-generic-handler@master
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
