services:
  mkics:
    image: jumpserver-east/mkics:${VERSION}
    container_name: mkics
    ulimits:
      core: 0
    ports:
      - "24916:24916"
    volumes:
      - ${VOLUME_DIR}/log:/opt/mkics/log
      - ${VOLUME_DIR}/config/:/opt/mkics/conf
    restart: always